# --- Project Specific Rules ---

# Keep JavaScript Interface for WebView
-keepclassmembers class com.example.socialonetwo.MainActivity$WebAppInterface {
    @android.webkit.JavascriptInterface <methods>;
}
-keep class com.example.socialonetwo.MainActivity$WebAppInterface

# --- Glide ---
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public class * extends com.bumptech.glide.module.LibraryGlideModule
-keep class com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
# The following class is generated by Glide at compile time
-keep class com.bumptech.glide.GeneratedAppGlideModuleImpl
-dontwarn com.bumptech.glide.load.resource.bitmap.VideoDecoder

# --- Firebase & GMS ---
# These are mostly handled by the libraries, but these prevent over-aggressive shrinking
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.firebase.**
-dontwarn com.google.android.gms.**

# --- General Android / AndroidX ---
-dontwarn androidx.**
-keep class androidx.lifecycle.ProcessLifecycleOwnerInitializer

# --- Attributes ---
-keepattributes SourceFile,LineNumberTable,Signature,AnnotationDefault,EnclosingMethod,InnerClasses,RuntimeVisibleAnnotations,RuntimeVisibleParameterAnnotations,RuntimeVisibleTypeAnnotations

# --- App Specific Components ---
# If you use custom model classes for Firestore, add them here
# -keep class com.example.socialonetwo.models.** { *; }
